" Disable vi-compatibility if it is not already disabled to avoid legacy quirks.
if &compatible
    set nocompatible
endif

" Custom Key Bindings

" Set the map leader key to space.
let mapleader=" "

" Set tab-related bindings
noremap <leader>n :tabn<CR>
noremap <leader>p :tabp<CR>
noremap <leader>1 1gt
noremap <leader>2 2gt
noremap <leader>3 3gt
noremap <leader>4 4gt
noremap <leader>5 5gt
noremap <leader>6 6gt
noremap <leader>7 7gt
noremap <leader>8 8gt
noremap <leader>9 9gt
noremap <leader>0 :tablast<cr>

" Set FZF and ripgrep bindings
nnoremap <leader>f :Files<CR>
nnoremap <leader>g :Rg<CR>
nnoremap <leader>b :Buffers<CR>

" Navigation

" Keep context lines visible above and below the cursor when scrolling.
set scrolloff=1

" Enable shell-like command-line completion.
set wildmenu
set wildmode=list:longest
set wildignore=*.o,*.obj,*.pdf

" Use system clipboard
set clipboard=unnamedplus

" Search

" Use case-insensitive search unless the query contains uppercase letters.
set ignorecase
set smartcase
set gdefault

" Highlight search terms and highlight as each key is pressed
set hlsearch

" Style

" Set the colorscheme to Dim (Default IMproved by @jkreeftmeijer)
colorscheme dim

" Enable the highlight on the cursor's current line
set cursorline

" Enable line numbers
set number

" Enable syntax highlighting if it is not already active.
if !exists("g:syntax_on")
    syntax enable
endif

" Display the cursor position and display partial commands
set ruler
set showcmd

" Limit the autocompletion menu height
set pumheight=10

" Configure the default spellcheck language
set spelllang=en_us

" Set the maximum line width to 128
set textwidth=128

" File-specific Styles
autocmd FileType gitconfig  setlocal noexpandtab
autocmd FileType javascript setlocal shiftwidth=2 softtabstop=2 tabstop=2
autocmd FileType make       setlocal noexpandtab
autocmd FileType python     setlocal shiftwidth=4 softtabstop=4 tabstop=4 expandtab
autocmd FileType puppet     setlocal shiftwidth=2 softtabstop=2 tabstop=2

" Plugins

" Enable vim-plug
call plug#begin('~/.vim/plugins')

Plug 'bling/vim-airline'
Plug 'easymotion/vim-easymotion'
Plug 'fatih/vim-go', { 'tag': '*' }
Plug 'junegunn/fzf.vim'
Plug 'rodjek/vim-puppet'
Plug 'tpope/vim-surround'

" vim-airline options
" Use powerline fonts for the powerline icons
let g:airline_powerline_fonts=1

" Always display the status line
set laststatus=2

" Load local plugin overrides.
if filereadable(expand("~/.vimrc.bundles.local"))
    source ~/.vimrc.bundles.local
endif

" Load plugins
call plug#end()

" Whitespace

" Remove trailing whitespace on save, except in filetypes where it is meaningful
" (e.g., Markdown hard line breaks, diff or patch context).
let g:trailing_whitespace_blacklist = ['markdown', 'diff', 'patch', 'mail', 'gitcommit']
autocmd BufWritePre * if index(g:trailing_whitespace_blacklist, &filetype) < 0 | keepjumps keeppatterns %s/\s\+$//e | endif

" Automatically indent new lines to match the previous line's indentation.
set autoindent

" Enable indentation matching
filetype plugin indent on

" Use 4-spaces instead of tab
set expandtab
set shiftwidth=4

" Set the tab's width to 4
set tabstop=4
set softtabstop=4

" Display tabs and trailing whitespaces visually.
set list
set listchars=tab:>·,trail:~

" Configure standard backspace behavior over line breaks and indents.
set backspace=eol,indent,start

" Miscellaneous

" Disable swap files and backup files
set noswapfile
set nobackup
set nowritebackup

" Automatically reload files modified outside of Vim.
set autoread

" Enable persistent undo history
if has("persistent_undo")
    set undodir=~/.vim/undo
    set undofile
endif

" Enable lazyredraw to prevent unnecessary redraws
set lazyredraw

" Map Tab and Shift-Tab to cycle through autocompletion suggestions.
function! InsertTabWrapper()
    let col = col('.') - 1
    if !col || getline('.')[col - 1] !~ '\k'
        return "\<tab>"
    else
        return "\<c-p>"
    endif
endfunction
inoremap <expr> <tab> InsertTabWrapper()
inoremap <expr> <s-tab> pumvisible() ? "\<c-n>" : "\<s-tab>"

" Map Leader + h/l to switch between open buffers.
nnoremap <leader>h :bprevious<CR>
nnoremap <leader>l :bnext<CR>

" Load local Vim overrides.
if filereadable(expand("~/.vimrc.local"))
    source ~/.vimrc.local
endif
