# .bash_profile

# Add Homebrew to the PATH if it exists.
if [[ -f "/opt/homebrew/bin/brew" ]]; then
    eval "$(/opt/homebrew/bin/brew shellenv)"
fi

# Source the shell-agnostic personal configurations.
source "$HOME/.profile"

# Source interactive non-login shell configurations.
source "$HOME/.bashrc"

# Initialize the fuzzy finder (fzf).
if command -v fzf > /dev/null; then
    eval "$(fzf --bash)"
fi
